### ISSUE TITLE
can not excute?

### ISSUE THREAD

**Issue by eexpress** [eleven26/ss-check#1]
⭕ curl https://raw.githubusercontent.com/eleven26/ss-check/master/install_update_linux.sh | bash
⭕ l /usr/local/bin/
ss-check
⭕ file /usr/local/bin/ss-check
/usr/local/bin/ss-check: Mach-O 64-bit x86_64 executable
⭕ ss-check -c ss-1.json 
bash: /usr/local/bin/ss-check：无法执行二进制文件: 可执行文件格式错误

**Comment by eleven26** [comment]
If you are not running under macOS, you need to clone the code and compile it

**Comment by eexpress** [comment]
Ubuntu 20.04.2 LTS.
